## This is the configuration file for Headroom.
## See https://github.com/vaclavsvejcar/headroom for more details.

## Defines the behaviour how to handle license headers, possible options are:
##   - add     = (default) adds license header to files with no existing header
##   - drop    = drops existing license header from without replacement
##   - replace = adds or replaces existing license header
run-mode: add

## Allows to change behaviour of license header detection.
license-headers:
  ## CSS configuration
  css:
    file-extensions: ["css"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: ['([^\r\n,{}]+)(,(?=[^}]*{)|\s*{)']
    block-comment:
      starts-with: "/*"
      ends-with: "*/"

  ## Haskell configuration
  haskell:
    file-extensions: ["hs"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: ["^module"]
    block-comment:
      starts-with: "{-|"
      ends-with: "-}"

  ## HTML configuration
  html:
    file-extensions: ["htm", "html"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: ["^(<!DOCTYPE|<[a-zA-Z])"]
    block-comment:
      starts-with: "<!--"
      ends-with: "-->"

  ## Java configuration
  java:
    file-extensions: ["java"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: ["^package"]
    block-comment:
      starts-with: "/*"
      ends-with: "*/"

  ## JS configuration
  js:
    file-extensions: ["js"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: []
    block-comment:
      starts-with: "/*"
      ends-with: "*/"

  ## Rust configuration
  rust:
    file-extensions: ["rs"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: []
    block-comment:
      starts-with: "/*"
      ends-with: "*/"

  ## Scala configuration
  scala:
    file-extensions: ["scala"]
    margin-after: 0
    margin-before: 0
    put-after: []
    put-before: ["^package"]
    block-comment:
      starts-with: "/*"
      ends-with: "*/"
