name: headroom
version: 0.1.0.0
homepage: https://github.com/vaclavsvejcar/headroom
license: BSD3
license-file: LICENSE
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: Copyright (c) 2019 Vaclav Svejcar

dependencies:
  - base >= 4.7 && < 5
  - data-default
  - optparse-applicative
  - rio

ghc-options:
  - -O2
  - -optP-Wno-nonportable-include-path
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror=incomplete-patterns

executables:
  headroom:
    main: Main.hs
    source-dirs: app
    dependencies:
      - headroom
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - aeson
    - either
    - extra
    - file-embed
    - ginger
    - pcre-heavy
    - pcre-light
    - template-haskell
    - text
    - time
    - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - headroom
      - hspec
  doctest:
    main: Main.hs
    source-dirs: doctest
    dependencies:
      - doctest
