name: headroom
version: 0.1.0.0
homepage: https://github.com/vaclavsvejcar/headroom
license: BSD3
license-file: LICENSE
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: Copyright (c) 2019 Vaclav Svejcar

executables:
  headroom:
    main: Main.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
