name: headroom
version: 0.1.0.0
homepage: https://github.com/vaclavsvejcar/headroom
license: BSD3
license-file: LICENSE
author: Vaclav Svejcar
maintainer: vaclav.svejcar@gmail.com
copyright: Copyright (c) 2019 Vaclav Svejcar

dependencies:
  - base >= 4.7 && < 5
  - containers

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  headroom:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - aeson
    - bytestring
    - yaml

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - headroom
      - hspec
